#!/usr/sbin/nft -f
# Ao fazer alguma alteracao executar o seguinte comando para aplicar:
# sudo nft -f /etc/nftables.conf
# E para verificar se a regra foi aplicada corretamente:
# sudo nft list ruleset

# Limpa todas as regras existentes
flush ruleset

# Cria uma tabela para IPv4 e IPv6
table inet filter {
    # Cadeia para tráfego de entrada
    chain input {
        type filter hook input priority filter; policy drop;

	# Bloqueia IPs
	ip saddr { 179.209.46.219, 172.237.152.151, 179.153.228.70 } log prefix "BLOCKED_IP: " drop

        # Aceita tráfego de loopback
        iif lo accept

        # Aceita conexões estabelecidas e relacionadas
        ct state established,related accept

        # Libera portas TCP
        tcp dport { 80, 443, 8080, 10023-10025, 17478, 20001-20005, 20010, 40001 } accept

        # Libera portas UDP
        udp dport { 3478, 4004, 8880, 10001, 10002, 10100-10199, 12345, 12346, 20001-20009, 21110, 30001-30007, 30051-30065, 40000, 42300, 42777, 62030 } accept

        # Rejeita todo o resto
        reject
    }

    # Cadeia para tráfego de saída (permite tudo por padrão)
    chain output {
        type filter hook output priority 0; policy accept;
    }

    # Cadeia para encaminhamento (bloqueia por padrão, se necessário)
    chain forward {
        type filter hook forward priority 0; policy drop;
    }
}
